# Generated by Django 3.0 on 2019-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('day', models.DateField(max_length=100)),
                ('started_at', models.TimeField(max_length=100)),
                ('ended_at', models.TimeField(max_length=100)),
                ('expectation', models.PositiveSmallIntegerField()),
                ('pleasure', models.PositiveSmallIntegerField()),
                ('achievement', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
